blank_issues_enabled: false
contact_links:
  - name: tse-guc-lab Slack Channel
    url: https://science-tokyo.enterprise.slack.com/archives/C055N7JHZQQ
    about: Ask questions or discuss issues directly with the team on Slack.
